### ISSUE TITLE
Update Todo Example

### ISSUE THREAD

**Issue by jeremyswann** [mongodb/stitch-examples#63]
It seems there have been some changes to Atlas since this tutorial was made, especially with Rules. I'm having trouble bridging the gap for permissions. Now instead of read and right rules there are now roles? I've read the [documentation](https://docs.mongodb.com/stitch/mongodb/mongodb-rules/) but I'm still getting errors on `npm start`. I'm sure I'm missing something, I've tried importing the stitch app provided but it won't import, might be out of date as previously stated.

**Comment by nlarew** [comment]
Hey @jeremyswann, thanks for the feedback!

As you've noticed, MongoDB service rules were refreshed in late June to reflect a role-based data access model. In the new system, Stitch first determines the role of each user that runs a query and then applies the read/write rules associated with that role to their query.

Did you find the existing rules documentation unclear? If so, I'd love to get some more details on what you found missing or confusing so that we can improve the docs moving forward. 😃

In regards to the ToDo app, would you mind providing a bit more information so that we can figure out where the issue is?

1. Which platform (Web, Android, or iOS) are you trying to build the ToDo app for? I assume web given that you're using `npm`, but want to confirm.
2. What error are you seeing when you run `npm start`?
3. What error are you seeing when you attempt to import the app configuration?

**Comment by enricocupellini** [comment]
iOS example not updated, not compile on Xcode 10.1.
step to reproduce the error 
- git clone from your repo
- run pod install on terminal
- found that your pod file is not updated 
- your pod file has conflicting libraries regards those pointed by my stichApp from mongoDB site
- tried to integrate the website pods (more recent versions) and Xcode not compile --> No such module 'MongoSwiftMobile'

**Comment by MongoCaleb** [comment]
@enricocupellini - the iOS todo app is undergoing a major refresh and will be released within the next week; I'll try to remember to update this issue when it's out. 
@jeremyswann  - are you still blocked with the node app?

**Comment by jeremyswann** [comment]
@nlarew I managed to setup rules and configure Atlas to my needs for my Production app, I didn't end up configuring the example, there were settings that moved around the UI that were presented elsewhere in the docs, however I eventually found them. I know it's hard to keep docs up to date 😉 so its all good.
@MongoCaleb I'm in production with my own app now so I'll close this Issue.
